#pragma once

#include "OVR_Math.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>
#include <stdexcept>

namespace QuestVr {

// This is the port's direct, unoccluded vertex-light approximation, shared by
// Quest and optional host previews. It is not UE1 lightmap/shadow reproduction.
struct MapLight {
    OVR::Vector3f localPosition;
    OVR::Vector3f color;
    OVR::Vector3f direction; // For cones/directional lights: light -> surface.
    float radiusMeters{};
    float intensity{};
    float coneCosine{-1.0f};
    // Explicit/manual directional lights have no radial falloff. The legacy
    // actor snapshot converter emits point/spot lights only; it does not infer
    // sunlight from names or invent unsupported authored light effects.
    bool directional{};
};

struct MapLightingConfig {
    OVR::Vector3f ambient{0.075f, 0.075f, 0.075f};
    float minimumChannel{0.04f};
    float maximumChannel{1.35f};
    float minimumDiffuse{0.04f};
};

inline bool ValidMapLightingConfig(const MapLightingConfig& config) noexcept {
    return std::isfinite(config.ambient.x) && std::isfinite(config.ambient.y) &&
        std::isfinite(config.ambient.z) && std::isfinite(config.minimumChannel) &&
        std::isfinite(config.maximumChannel) && std::isfinite(config.minimumDiffuse) &&
        config.minimumChannel >= 0.0f && config.maximumChannel >= config.minimumChannel &&
        config.minimumDiffuse >= 0.0f && config.minimumDiffuse <= 1.0f;
}

struct MapLightBuildStats {
    std::size_t total{};
    std::size_t spotlights{};
    std::size_t colored{};
    std::size_t invalidLocations{};
    std::array<std::size_t,256> lightTypeCounts{};
    std::array<std::size_t,256> lightEffectCounts{};
    OVR::Vector3f unrealOrigin{-1149.244f, 825.844f, -65.103f};
};

inline bool FiniteMapLightVector(const OVR::Vector3f& value) noexcept {
    return std::isfinite(value.x) && std::isfinite(value.y) && std::isfinite(value.z);
}

inline OVR::Vector3f UnrealMapToQuestPosition(
    const OVR::Vector3f& position, const OVR::Vector3f& origin) noexcept {
    constexpr float unitsToMeters = 1.0f / 52.5f;
    return {(position.y - origin.y) * unitsToMeters,
            (position.z - origin.z) * unitsToMeters + 1.0f,
            -(position.x - origin.x) * unitsToMeters};
}

inline OVR::Vector3f UnrealMapLightDirection(
    const std::int32_t yawUnits, const std::int32_t pitchUnits) noexcept {
    constexpr float unrealAngle = 6.28318530717958647692f / 65536.0f;
    const float yaw = static_cast<float>(yawUnits) * unrealAngle;
    const float pitch = static_cast<float>(pitchUnits) * unrealAngle;
    const float cosinePitch = std::cos(pitch);
    return {cosinePitch * std::sin(yaw), std::sin(pitch),
            -cosinePitch * std::cos(yaw)};
}

inline OVR::Vector3f UnrealMapHsbColor(const std::uint8_t hue,
    const std::uint8_t unrealSaturation, const std::uint8_t brightness) noexcept {
    // Pinned SurrealEngine Math/hsb.h uses three linear hue sectors rather than
    // conventional six-sector HSV. Its hsb.cpp table is generated by this sqrt
    // expression, rounded to six decimals; host tests compare every table value.
    const float value = 6.512735f * std::sqrt(static_cast<float>(brightness));
    if (unrealSaturation >= 250u) return OVR::Vector3f(value * (1.0f / 255.0f));
    if (brightness == 0u) return OVR::Vector3f(0.0f);
    float saturation = static_cast<float>(unrealSaturation) * (1.0f / 2.5f);
    if (saturation > 32.0f) saturation += 2.0f;
    const float sectorPosition = static_cast<float>(hue) * (1.0f / 85.0f);
    const int sector = static_cast<int>(sectorPosition);
    const float fraction = sectorPosition - static_cast<float>(sector);
    const float p = saturation * value * (1.0f / 104.0f);
    const float q = (1.0f - fraction) * value + p * fraction;
    const float t = fraction * value + p * (1.0f - fraction);
    constexpr float byteToChannel = 1.0f / 255.0f;
    if (hue < 85u) return {q*byteToChannel,t*byteToChannel,p*byteToChannel};
    if (hue < 170u) return {p*byteToChannel,q*byteToChannel,t*byteToChannel};
    return {t*byteToChannel,p*byteToChannel,q*byteToChannel};
}

inline OVR::Vector3f UnrealMapLightColor(
    const std::uint8_t hue, const std::uint8_t unrealSaturation) noexcept {
    // Keep the port's brightness/64 direct-light intensity gain separate from
    // normalized authored hue/saturation. Applying raw HSB brightness here as
    // well would apply brightness twice. Exact HSB brightness is available above
    // for audits; photometric gain/zone lighting remain an approximation.
    const OVR::Vector3f color = UnrealMapHsbColor(hue, unrealSaturation, 255u);
    const float white = UnrealMapHsbColor(0u, 255u, 255u).x;
    return color * (1.0f / white);
}

inline float UnrealMapLightConeCosine(const std::uint8_t cone) noexcept {
    // UE1 stores the outer cosine indirectly, not an angle in degrees. Match
    // pinned SurrealEngine Light/LightEffect.cpp SpotlightEffect's conversion.
    // Cone 128 is approximately 60 degrees, not the prior port's 89 degrees;
    // cone 0 is an empty beam and cone 255 reaches a hemisphere. Falloff below
    // remains the port's direct vertex approximation, without UE1 lightmaps.
    return 1.0f - static_cast<float>(cone) * (1.0f / 255.0f);
}

// Deliberately templated: PortableActorSnapshot can be passed directly, without
// making this CPU-only header depend on the engine/GC/package headers. Fixtures
// need only the snapshot's lighting/location/class fields.
template <class ActorSnapshot>
inline std::vector<MapLight> BuildMapLights(
    const std::vector<ActorSnapshot>& actors, MapLightBuildStats* stats = nullptr,
    const OVR::Vector3f* verifiedOrigin = nullptr) {
    MapLightBuildStats resultStats;
    if (verifiedOrigin) {
        if (!FiniteMapLightVector(*verifiedOrigin)) throw std::invalid_argument("Non-finite verified map origin");
        resultStats.unrealOrigin = *verifiedOrigin;
    }
    for (const auto& actor : actors) {
        if (verifiedOrigin) break;
        const std::size_t separator = actor.classPath.find_last_of('.');
        const std::string leafClass = separator == std::string::npos
            ? actor.classPath : actor.classPath.substr(separator + 1u);
        if (actor.hasLocation && leafClass == "PlayerStart" &&
            FiniteMapLightVector({actor.x, actor.y, actor.z})) {
            resultStats.unrealOrigin = {actor.x, actor.y, actor.z};
            break;
        }
    }
    std::vector<MapLight> lights;
    for (const auto& actor : actors) {
        if (!actor.light || !actor.hasLocation || actor.lightType == 0u ||
            actor.lightBrightness == 0u) continue;
        if (!FiniteMapLightVector({actor.x, actor.y, actor.z})) {
            ++resultStats.invalidLocations;
            continue;
        }
        MapLight light;
        light.localPosition = UnrealMapToQuestPosition(
            {actor.x, actor.y, actor.z}, resultStats.unrealOrigin);
        light.color = UnrealMapLightColor(actor.lightHue, actor.lightSaturation);
        constexpr float unitsToMeters = 1.0f / 52.5f;
        // Pinned UActor::WorldLightRadius includes one extra radius unit. A
        // radius byte of zero still illuminates 25 Unreal units; it is not an
        // off switch (LightType/LightBrightness provide that).
        light.radiusMeters = (static_cast<float>(actor.lightRadius) + 1.0f) *
            25.0f * unitsToMeters;
        light.intensity = std::clamp(
            static_cast<float>(actor.lightBrightness) / 64.0f, 0.05f, 4.0f);
        if (actor.lightEffect == 8u || actor.lightEffect == 12u) {
            light.direction = UnrealMapLightDirection(actor.yaw, actor.pitch);
            light.coneCosine = UnrealMapLightConeCosine(actor.lightCone);
            ++resultStats.spotlights;
        }
        if (actor.lightSaturation < 224u) ++resultStats.colored;
        ++resultStats.lightTypeCounts[actor.lightType];
        ++resultStats.lightEffectCounts[actor.lightEffect];
        lights.push_back(light);
    }
    resultStats.total = lights.size();
    if (stats != nullptr) *stats = resultStats;
    return lights;
}

inline OVR::Vector3f CalculateMapLighting(
    const std::vector<MapLight>& lights, const OVR::Vector3f& position,
    const OVR::Vector3f& normal, const MapLightingConfig& config = {}) noexcept {
    // Invalid explicit configuration must not create NaN output or violate
    // std::clamp's ordered-bound precondition. Native uses the valid defaults.
    const MapLightingConfig settings = ValidMapLightingConfig(config)
        ? config : MapLightingConfig{};
    OVR::Vector3f result = settings.ambient;
    // Native cache normals are unit length. Preserve their existing diffuse
    // behavior (including the small backface floor) rather than adding a
    // different light model in host previews.
    if (FiniteMapLightVector(position) && FiniteMapLightVector(normal)) {
        for (const MapLight& light : lights) {
            if (!FiniteMapLightVector(light.color) || !std::isfinite(light.intensity) ||
                light.intensity <= 0.0f || !std::isfinite(light.coneCosine)) continue;
            OVR::Vector3f direction;
            float distanceFade = 1.0f;
            if (light.directional) {
                const float lengthSquared = light.direction.LengthSq();
                if (!FiniteMapLightVector(light.direction) || !std::isfinite(lengthSquared) ||
                    lengthSquared <= 0.000001f) continue;
                direction = light.direction.Normalized() * -1.0f;
            } else {
                if (!FiniteMapLightVector(light.localPosition) ||
                    !std::isfinite(light.radiusMeters) || light.radiusMeters <= 0.0f) continue;
                const OVR::Vector3f offset = light.localPosition - position;
                const float distanceSquared = offset.LengthSq();
                if (!std::isfinite(distanceSquared) || distanceSquared <= 0.000001f ||
                    distanceSquared >= light.radiusMeters * light.radiusMeters) continue;
                const float distance = std::sqrt(distanceSquared);
                direction = offset * (1.0f / distance);
                distanceFade = 1.0f - distance / light.radiusMeters;
            }
            float cone = 1.0f;
            if (!light.directional && light.coneCosine >= 0.0f) {
                if (!FiniteMapLightVector(light.direction) ||
                    !std::isfinite(light.coneCosine) || light.coneCosine >= 1.0f) continue;
                const float alignment = (direction * -1.0f).Dot(light.direction);
                if (alignment <= light.coneCosine) continue;
                cone = std::clamp((alignment - light.coneCosine) /
                    (1.0f - light.coneCosine), 0.0f, 1.0f);
            }
            const float diffuse = std::max(settings.minimumDiffuse, normal.Dot(direction));
            const float contribution = light.intensity * distanceFade * distanceFade * diffuse * cone;
            result.x += light.color.x * contribution;
            result.y += light.color.y * contribution;
            result.z += light.color.z * contribution;
        }
    }
    result.x = std::clamp(result.x, settings.minimumChannel, settings.maximumChannel);
    result.y = std::clamp(result.y, settings.minimumChannel, settings.maximumChannel);
    result.z = std::clamp(result.z, settings.minimumChannel, settings.maximumChannel);
    return result;
}

} // namespace QuestVr
